name: 勉強会登録
description: IT勉強会やイベントをカレンダーに登録するためのフォーム
title: "[勉強会登録] "
labels: ["it-study-session"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## IT勉強会カレンダーへの登録

        IT関連の勉強会やイベントをカレンダーに登録します。
        以下の項目を入力してください。

  - type: input
    id: title
    attributes:
      label: 勉強会タイトル
      description: 勉強会のタイトルを入力してください
      placeholder: 例：おもにクラウドの話してます #1
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: 勉強会ページのリンク
      description: connpassやDoorkeeperなどのイベントページのURLを入力してください
      placeholder: 例：https://connpass.com/event/123456/
    validations:
      required: true

  - type: input
    id: datetime
    attributes:
      label: 開催日時
      description: 開催日時を入力してください
      placeholder: 例：2024年7月15日 19:00-21:00
    validations:
      required: true
