name: Add Hiroshima Study Session to Calendar

on:
  issues:
    types: [closed]

jobs:
  add-to-calendar:
    if: github.event.issue.state == 'closed' && github.event.issue.state_reason == 'completed' && contains(github.event.issue.labels.*.name, 'hiroshima-study-session')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Parse Issue Content
        id: parse
        run: |
          # Issueの内容を解析してイベント情報を抽出
          echo "Parsing issue content..."
          
          # Issue番号とタイトルを取得
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
          echo "issue_title=$ISSUE_TITLE" >> $GITHUB_OUTPUT
          
          # ここで実際のIssue内容を解析してカレンダーイベントの情報を抽出
          # 本格実装時は、Issue本文から日時、URL、説明などを正規表現で抽出
          echo "Parsed issue content for issue #$ISSUE_NUMBER"

      - name: Add to Google Calendar
        run: |
          echo "Adding event to Google Calendar..."
          echo "Issue: ${{ steps.parse.outputs.issue_title }}"
          echo "Issue Number: ${{ steps.parse.outputs.issue_number }}"
          
          # 実際のGoogle Calendar API呼び出しはここに実装
          # 以下は実装例のコメント:
          # 
          # curl -X POST \
          #   "https://www.googleapis.com/calendar/v3/calendars/${{ secrets.GOOGLE_CALENDAR_ID }}/events" \
          #   -H "Authorization: Bearer ${{ secrets.GOOGLE_CALENDAR_API_KEY }}" \
          #   -H "Content-Type: application/json" \
          #   -d '{
          #     "summary": "勉強会タイトル",
          #     "description": "勉強会の説明とURL",
          #     "start": {
          #       "dateTime": "2024-07-15T19:00:00+09:00",
          #       "timeZone": "Asia/Tokyo"
          #     },
          #     "end": {
          #       "dateTime": "2024-07-15T21:00:00+09:00", 
          #       "timeZone": "Asia/Tokyo"
          #     }
          #   }'
          
          echo "Event added successfully (placeholder)"

      - name: Comment on Issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ 広島の勉強会がカレンダーに追加されました！\n\nカレンダーページで確認できます: https://satoshi256kbyte.github.io/it-study-session-calendar/'
            })
