name: Cleanup PNG Files

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Remove converted PNG files if they exist
        run: |
          # Check if converted_images directory exists
          if [ -d "converted_images" ]; then
            echo "Found converted_images directory, removing it..."
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            
            # Remove the directory
            rm -rf converted_images/
            
            # Commit the removal
            git add -A
            git commit -m "Clean up converted PNG files after PR #${{ github.event.pull_request.number }} merge [skip ci]" || echo "No files to clean up"
            
            # Push to main
            git push origin main
          else
            echo "No converted_images directory found, nothing to clean up"
          fi
