name: Deploy Calendar to GitHub Pages

on:
  push:
    branches: [main]
    paths: ['calendar/**']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'
          cache: 'npm'
          cache-dependency-path: calendar/package-lock.json

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            calendar/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('calendar/package.json') }}-${{ hashFiles('calendar/**.[jt]s', 'calendar/**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('calendar/package.json') }}-

      - name: Clean install dependencies
        run: |
          cd calendar
          # Remove any existing node_modules and package-lock.json
          rm -rf node_modules package-lock.json .next
          # Create a temporary .npmrc to ignore workspace config
          echo "workspaces=false" > .npmrc
          # Install dependencies
          npm ci --prefer-offline --no-audit --no-fund
          # Remove temporary .npmrc
          rm -f .npmrc
        env:
          CI: true
          NEXT_TELEMETRY_DISABLED: 1

      - name: Debug environment variables
        run: |
          echo "API_BASE_URL: ${{ secrets.API_BASE_URL }}"
          echo "GOOGLE_CALENDAR_URL: ${{ secrets.GOOGLE_CALENDAR_URL }}"

      - name: Build with Next.js
        run: |
          cd calendar
          # Set environment variables
          export NEXT_TELEMETRY_DISABLED=1
          export NODE_ENV=production
          # Create a temporary .npmrc to ignore workspace config
          echo "workspaces=false" > .npmrc
          # Build the application
          npx next build --no-lint
          # Remove temporary .npmrc
          rm -f .npmrc
          # Copy assets manually
          mkdir -p out
          cp -r assets/* out/ 2>/dev/null || true
        env:
          NEXT_PUBLIC_GOOGLE_CALENDAR_URL: ${{ secrets.GOOGLE_CALENDAR_URL }}
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.API_BASE_URL }}
          NEXT_TELEMETRY_DISABLED: 1
          NODE_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./calendar/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
